driver:
  name: vagrant
  require_chef_omnibus: 13.12.14

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: client
    run_list:
      - recipe[mysql_test::client]
  - name: ruby
    run_list:
      - recipe[mysqlx::ruby]
  - name: server
    run_list:
      - recipe[apt]
      - recipe[mysql_test::server]
    attributes:
      apt:
        compile_time_update: true
      mysqlx:
        tunable:
          log_bin: true
          replicate_do_db: "tv_chef"
          replicate_do_table: "tv_chef.tv_chef"
          replicate_ignore_db: "mysql_test"
          replicate_ignore_table: "tv_chef.test"
          replicate_wild_do_table: "tv_chef.tv%"
          replicate_wild_ignore_table: "tv_chef.test%"
          skip_slave_start: true
          open_files_limit: 102400
  - name: server-datadir
    run_list:
      - recipe[mysql_test::server]
    attributes:
      mysqlx:
        data_dir: "/data/mysql"
