driver:
  name: vagrant
  require_chef_omnibus: 13.12.14

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: client
    run_list:
      - recipe[mysql_test::client]
  - name: ruby
    run_list:
      - recipe[mysqlx::ruby]
  - name: server
    run_list:
      - recipe[mysql_test::server]
  - name: server-datadir
    run_list:
      - recipe[mysql_test::server]
    attributes:
      mysql:
        data_dir: "/data/mysql"
